//-----------------------------------------------------------
//  Finite State Machines
//-----------------------------------------------------------
//
//      fsm.cpp           v1.00
//
//      A template defining finite state machine types.
//
//-----------------------------------------------------------
//  Copyright 1995 by Scott Robert Ladd. All rights reserved.
//-----------------------------------------------------------

#include "fsm.h"

void FSM_Ex::Explain
    (
    DiagOutput & out
    )
    {
    out.DisplayMsg("Finite State Machine exception",DIAG_ERROR);
    }


